"""add northwind models

Revision ID: 82107b1b46b7
Revises: ec48bb74a747
Create Date: 2024-01-01 07:56:14.455308

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '82107b1b46b7'
down_revision = 'ec48bb74a747'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        'categories',
        sa.Column('category_id', sa.Integer(), nullable=False),
        sa.Column('category_name', sa.String(length=15), nullable=False),
        sa.Column('description', sa.Text(), nullable=True),
        sa.Column('picture', sa.LargeBinary(), nullable=True),
        sa.PrimaryKeyConstraint('category_id', name='categories_pkey'),
    )
    op.create_table(
        'customer_demographics',
        sa.Column('customer_type_id', sa.String(length=5), nullable=False),
        sa.Column('customer_desc', sa.Text(), nullable=True),
        sa.PrimaryKeyConstraint('customer_type_id', name='pk_customer_demographics'),
    )
    op.create_table(
        'customers',
        sa.Column('customer_id', sa.String(length=5), nullable=False),
        sa.Column('company_name', sa.String(length=40), nullable=False),
        sa.Column('contact_name', sa.String(length=30), nullable=True),
        sa.Column('contact_title', sa.String(length=30), nullable=True),
        sa.Column('address', sa.String(length=60), nullable=True),
        sa.Column('city', sa.String(length=15), nullable=True),
        sa.Column('region', sa.String(length=15), nullable=True),
        sa.Column('postal_code', sa.String(length=10), nullable=True),
        sa.Column('country', sa.String(length=15), nullable=True),
        sa.Column('phone', sa.String(length=24), nullable=True),
        sa.Column('fax', sa.String(length=24), nullable=True),
        sa.PrimaryKeyConstraint('customer_id', name='pk_customers'),
    )
    op.create_table(
        'employees',
        sa.Column('employee_id', sa.Integer(), nullable=False),
        sa.Column('last_name', sa.String(length=20), nullable=False),
        sa.Column('first_name', sa.String(length=10), nullable=False),
        sa.Column('title', sa.String(length=30), nullable=True),
        sa.Column('title_of_courtesy', sa.String(length=25), nullable=True),
        sa.Column('birth_date', sa.Date(), nullable=True),
        sa.Column('hire_date', sa.Date(), nullable=True),
        sa.Column('address', sa.String(length=60), nullable=True),
        sa.Column('city', sa.String(length=15), nullable=True),
        sa.Column('region', sa.String(length=15), nullable=True),
        sa.Column('postal_code', sa.String(length=10), nullable=True),
        sa.Column('country', sa.String(length=15), nullable=True),
        sa.Column('home_phone', sa.String(length=24), nullable=True),
        sa.Column('extension', sa.String(length=4), nullable=True),
        sa.Column('photo', sa.LargeBinary(), nullable=True),
        sa.Column('notes', sa.Text(), nullable=True),
        sa.Column('reports_to', sa.SmallInteger(), nullable=True),
        sa.Column('photo_path', sa.String(length=255), nullable=True),
        sa.ForeignKeyConstraint(['reports_to'], ['employees.employee_id'], name='fk_employees_employees'),
        sa.PrimaryKeyConstraint('employee_id', name='employees_pkey'),
    )
    op.create_table(
        'region',
        sa.Column('region_id', sa.Integer(), nullable=False),
        sa.Column('region_description', sa.String(length=60), nullable=False),
        sa.PrimaryKeyConstraint('region_id', name='region_pkey'),
    )
    op.create_table(
        'shippers',
        sa.Column('shipper_id', sa.Integer(), nullable=False),
        sa.Column('company_name', sa.String(length=40), nullable=False),
        sa.Column('phone', sa.String(length=24), nullable=True),
        sa.PrimaryKeyConstraint('shipper_id', name='shippers_pkey'),
    )
    op.create_table(
        'suppliers',
        sa.Column('supplier_id', sa.Integer(), nullable=False),
        sa.Column('company_name', sa.String(length=40), nullable=False),
        sa.Column('contact_name', sa.String(length=30), nullable=True),
        sa.Column('contact_title', sa.String(length=30), nullable=True),
        sa.Column('address', sa.String(length=60), nullable=True),
        sa.Column('city', sa.String(length=15), nullable=True),
        sa.Column('region', sa.String(length=15), nullable=True),
        sa.Column('postal_code', sa.String(length=10), nullable=True),
        sa.Column('country', sa.String(length=15), nullable=True),
        sa.Column('phone', sa.String(length=24), nullable=True),
        sa.Column('fax', sa.String(length=24), nullable=True),
        sa.Column('homepage', sa.Text(), nullable=True),
        sa.PrimaryKeyConstraint('supplier_id', name='suppliers_pkey'),
    )
    op.create_table(
        'us_states',
        sa.Column('state_id', sa.Integer(), nullable=False),
        sa.Column('state_name', sa.String(length=100), nullable=True),
        sa.Column('state_abbr', sa.String(length=2), nullable=True),
        sa.Column('state_region', sa.String(length=50), nullable=True),
        sa.PrimaryKeyConstraint('state_id', name='us_states_pkey'),
    )
    op.create_table(
        'customer_customer_demo',
        sa.Column('customer_id', sa.String(length=5), nullable=False),
        sa.Column('customer_type_id', sa.String(length=5), nullable=False),
        sa.ForeignKeyConstraint(['customer_id'], ['customers.customer_id'], name='fk_customer_customer_demo_customers'),
        sa.ForeignKeyConstraint(
            ['customer_type_id'],
            ['customer_demographics.customer_type_id'],
            name='fk_customer_customer_demo_customer_demographics',
        ),
        sa.PrimaryKeyConstraint('customer_id', 'customer_type_id', name='pk_customer_customer_demo'),
    )
    op.create_table(
        'orders',
        sa.Column('order_id', sa.Integer(), nullable=False),
        sa.Column('customer_id', sa.String(length=5), nullable=True),
        sa.Column('employee_id', sa.SmallInteger(), nullable=True),
        sa.Column('order_date', sa.Date(), nullable=True),
        sa.Column('required_date', sa.Date(), nullable=True),
        sa.Column('shipped_date', sa.Date(), nullable=True),
        sa.Column('ship_via', sa.SmallInteger(), nullable=True),
        sa.Column('freight', sa.Float(), nullable=True),
        sa.Column('ship_name', sa.String(length=40), nullable=True),
        sa.Column('ship_address', sa.String(length=60), nullable=True),
        sa.Column('ship_city', sa.String(length=15), nullable=True),
        sa.Column('ship_region', sa.String(length=15), nullable=True),
        sa.Column('ship_postal_code', sa.String(length=10), nullable=True),
        sa.Column('ship_country', sa.String(length=15), nullable=True),
        sa.ForeignKeyConstraint(['customer_id'], ['customers.customer_id'], name='fk_orders_customers'),
        sa.ForeignKeyConstraint(['employee_id'], ['employees.employee_id'], name='fk_orders_employees'),
        sa.ForeignKeyConstraint(['ship_via'], ['shippers.shipper_id'], name='fk_orders_shippers'),
        sa.PrimaryKeyConstraint('order_id', name='orders_pkey'),
    )
    op.create_table(
        'products',
        sa.Column('product_id', sa.Integer(), nullable=False),
        sa.Column('product_name', sa.String(length=40), nullable=False),
        sa.Column('supplier_id', sa.SmallInteger(), nullable=True),
        sa.Column('category_id', sa.SmallInteger(), nullable=True),
        sa.Column('quantity_per_unit', sa.String(length=20), nullable=True),
        sa.Column('unit_price', sa.Float(), nullable=True),
        sa.Column('units_in_stock', sa.SmallInteger(), nullable=True),
        sa.Column('units_on_order', sa.SmallInteger(), nullable=True),
        sa.Column('reorder_level', sa.SmallInteger(), nullable=True),
        sa.Column('discontinued', sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(['category_id'], ['categories.category_id'], name='fk_products_categories'),
        sa.ForeignKeyConstraint(['supplier_id'], ['suppliers.supplier_id'], name='fk_products_suppliers'),
        sa.PrimaryKeyConstraint('product_id', name='products_pkey'),
    )
    op.create_table(
        'territories',
        sa.Column('territory_id', sa.String(length=20), nullable=False),
        sa.Column('territory_description', sa.String(length=60), nullable=False),
        sa.Column('region_id', sa.SmallInteger(), nullable=False),
        sa.ForeignKeyConstraint(['region_id'], ['region.region_id'], name='fk_territories_region'),
        sa.PrimaryKeyConstraint('territory_id', name='pk_territories'),
    )
    op.create_table(
        'employee_territories',
        sa.Column('employee_id', sa.SmallInteger(), nullable=False),
        sa.Column('territory_id', sa.String(length=20), nullable=False),
        sa.ForeignKeyConstraint(['employee_id'], ['employees.employee_id'], name='fk_employee_territories_employees'),
        sa.ForeignKeyConstraint(
            ['territory_id'], ['territories.territory_id'], name='fk_employee_territories_territories'
        ),
        sa.PrimaryKeyConstraint('employee_id', 'territory_id', name='pk_employee_territories'),
    )
    op.create_table(
        'order_details',
        sa.Column('order_id', sa.SmallInteger(), nullable=False),
        sa.Column('product_id', sa.SmallInteger(), nullable=False),
        sa.Column('unit_price', sa.Float(), nullable=False),
        sa.Column('quantity', sa.SmallInteger(), nullable=False),
        sa.Column('discount', sa.Float(), nullable=False),
        sa.ForeignKeyConstraint(['order_id'], ['orders.order_id'], name='fk_order_details_orders'),
        sa.ForeignKeyConstraint(['product_id'], ['products.product_id'], name='fk_order_details_products'),
        sa.PrimaryKeyConstraint('order_id', 'product_id', name='pk_order_details'),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('order_details')
    op.drop_table('employee_territories')
    op.drop_table('territories')
    op.drop_table('products')
    op.drop_table('orders')
    op.drop_table('customer_customer_demo')
    op.drop_table('us_states')
    op.drop_table('suppliers')
    op.drop_table('shippers')
    op.drop_table('region')
    op.drop_table('employees')
    op.drop_table('customers')
    op.drop_table('customer_demographics')
    op.drop_table('categories')
    # ### end Alembic commands ###
